'use server';

/**
 * @fileOverview Recommends spiritual videos based on the user's watch history.
 *
 * - getVideoRecommendations - A function that returns video recommendations.
 * - VideoRecommendationsInput - The input type for the getVideoRecommendations function.
 * - VideoRecommendationsOutput - The return type for the getVideoRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VideoRecommendationsInputSchema = z.object({
  videoWatchHistory: z.array(z.string()).describe('An array of video titles the user has watched.'),
});
export type VideoRecommendationsInput = z.infer<typeof VideoRecommendationsInputSchema>;

const VideoRecommendationsOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      videoId: z.string().describe('The ID of the recommended video.'),
      title: z.string().describe('The title of the recommended video.'),
      reason: z.string().describe('A short reason why this video is recommended.'),
    })
  ).describe('An array of video recommendations.'),
});
export type VideoRecommendationsOutput = z.infer<typeof VideoRecommendationsOutputSchema>;

export async function getVideoRecommendations(input: VideoRecommendationsInput): Promise<VideoRecommendationsOutput> {
  return videoRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'videoRecommendationsPrompt',
  input: {schema: VideoRecommendationsInputSchema},
  output: {schema: VideoRecommendationsOutputSchema},
  prompt: `You are an expert in spiritual and wellness content. Based on the user's watch history, you will recommend other relevant videos on the aaura platform.

  Video Watch History:
  {{#each videoWatchHistory}}
  - {{{this}}}
  {{/each}}

  Please provide a list of video recommendations based on the user's video watch history. Focus on videos with similar themes, creators, or spiritual topics. For each recommendation, provide a brief, compelling reason for the user.
`,
});

const videoRecommendationsFlow = ai.defineFlow(
  {
    name: 'videoRecommendationsFlow',
    inputSchema: VideoRecommendationsInputSchema,
    outputSchema: VideoRecommendationsOutputSchema,
  },
  async input => {
    // In a real application, you would add logic here to find actual video IDs from your database
    // based on the titles generated by the model.
    const {output} = await prompt(input);
    return output!;
  }
);
